### ISSUE TITLE
Link repo cards to repos

### ISSUE THREAD

**Issue by ghost** [Preet-Sojitra/Preet-Sojitra#2]
Just a suggestion; on your repo cards (profile README.md) you could link the repository cards to the repositories rather than the repo with the card source. It would make a bit more sense to the user and fulfill the card's true function: to provide more repo pins on your profile.

I've gone ahead and opened a PR here: #1

**Comment by Preet-Sojitra** [comment]
Thank you for your suggestion. I already have this in mind to fix the link of repo cards but I was busy in some other work I was not able do it.
